### ISSUE TITLE
Line number seems to be off by -1

### ISSUE THREAD

**Issue by zommerfelds** [devsearch-epfl/devsearch-play#17]
Maybe our lines are 0 based, whereas GitHub is 1 based?
e.g. `class Message {}`

**Comment by paullepoulpe** [comment]
Our line numbering doesn't seem consistent 

Scala seems to be off by one:
![screenshot 2015-05-11 17 59 37](https://cloud.githubusercontent.com/assets/1906266/7569226/a007e7e4-f807-11e4-9ee4-aba2a986d0ae.png)

Java seems fine:
![screenshot 2015-05-11 17 59 52](https://cloud.githubusercontent.com/assets/1906266/7569227/a009f0d4-f807-11e4-8dcc-356bd5568558.png)

**Comment by zommerfelds** [comment]
Actually this could be due to the files changing since the DevMine download. Is it consistent across all entries?

**Comment by samarion** [comment]
No, it's indeed the parsers. Scala positions are 0-indexed and Java are 1-indexed.

**Comment by samarion** [comment]
Fixed in https://github.com/devsearch-epfl/devsearch-ast/pull/38, now all positions are 0-indexed
